version: '3'
services:
  validator:
    extends:
      file: ../docker-compose.common.yml
      service: app
    build:
      args:
        SETTINGS_FILEPATH: bscvault-validator/settings.js
    ports:
      - 18985:8984
    networks:
      - br-bscvalidator

networks:
    br-bscvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.131.0/24
