version: '3'
services:
  validator:
    build:
      context: ../
      dockerfile: ./terravault-validator/Dockerfile
    ports:
      - 28985:8984
    networks:
      - br-terravalidator

networks:
    br-terravalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 11.2.1.0/24