version: '3'
services:
  validator:
    build:
      context: ../
      dockerfile: ./ethvault-validator/Dockerfile
    ports:
      - 18985:8984
    networks:
      - br-ethvalidator
    env_file:
      - ../.env

networks:
    br-ethvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.127.0/24