version: '3'
services:
  validator:
    extends:
      file: common.yml
      service: app
    build:
      args:
        SETTINGS_FILEPATH: ethvault-validator/settings.js
        PM2_ECOSYSTEM_FILEPATH: ethvault-validator/pm2.yaml
    ports:
      - 18985:8984
    networks:
      - br-ethvalidator

networks:
    br-ethvalidator:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.127.0/24
